apiVersion: v1
kind: Service
metadata:
  name: tesla-dashboard-ui-service
spec:
  selector:
    app: tesla-dashboard-ui
  ports:
    - protocol: TCP
      port: 80    # Exposing port 80 on the Service
      targetPort: 3000   # The port the app inside the pod is using
  type: LoadBalancer
