apiVersion: v1
kind: Service
metadata:
  name: tesla-dashboard-ui-service
spec:
  selector:
    app: tesla-dashboard-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Make sure this is the port the app inside the pod is using
  type: NodePort   # Change this to NodePort instead of LoadBalancer
