apiVersion: v1
kind: Service
metadata:
  name: tesla-dashboard-ui-service
spec:
  selector:
    app: tesla-dashboard-ui
  ports:
    - protocol: TCP
      port: 80          # External port exposed by the service
      targetPort: 3000   # Internal port where the app is running inside the pod
  type: LoadBalancer
