apiVersion: v1
kind: Service
metadata:
  name: tesla-dashboard-ui-service
spec:
  selector:
    app: tesla-dashboard-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
